// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewbzkxfxsuehvyyaeuze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3YnpreGZ4c3VlaHZ5eWFldXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNDU0MjQsImV4cCI6MjA2MTkyMTQyNH0.DkRf4-DtFpidCHYnfQqfK0UlSGH0Q9a8uZsymhbgrE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);